{"ApiActionName":"account","RequestContent":"{\"ID\":19,\"FirstName\":\"کریم1\",\"LastName\":\"پازوکی1\",\"UserName\":\"user2\",\"UserType\":1000,\"IsActive\":true,\"Password\":\"1\"}","RequestContentType":null,"RequestUri":"http://localhost:65403/api/account","RequestMethod":"PUT","RequestTimestamp":"2020-07-18T16:23:20.1608602+04:30","ResponseContent":"{\"ResultCode\":3,\"Messages\":[\"An error occurred while updating the entries. See the inner exception for details.\"],\"Data\":null}","ResponseContentType":"application/json","ResponseStatusCode":500,"ResponseTimestamp":"2020-07-18T16:23:20.4328743+04:30"}