{"ApiActionName":"account","RequestContent":"{\"FirstName\":\"علی\",\"LastName\":\"کریمی\",\"UserName\":\"user1\",\"Password\":\"1\",\"UserType\":2,\"IsActive\":true}","RequestContentType":null,"RequestUri":"http://localhost:65403/api/account","RequestMethod":"POST","RequestTimestamp":"2020-07-18T16:12:54.2344536+04:30","ResponseContent":"{\"ResultCode\":3,\"Messages\":[\"An error occurred while updating the entries. See the inner exception for details.\"],\"Data\":null}","ResponseContentType":"application/json","ResponseStatusCode":500,"ResponseTimestamp":"2020-07-18T16:16:05.3891454+04:30"}